sudo: false
language: python
python:
  - "2.7"
  - "3.5"
# TODO(patrick): Test on OSX, python is not supported on travis yet
# os:
  # - linux
  # - osx
cache:
  pip: true

addons:
  apt:
    packages:
      # numpy and scipy cause a lot of trouble and are expensive to install, so install
      # them once for all packages, and let the virtualenvs see this parent package
      - 'python-numpy'
      - 'python-scipy'

before_script:
  - python -c "import numpy; print(numpy.__version__)"
  - python -c "import scipy; print(scipy.__version__)"

# Use the SIGOPT_API_TOKEN environment variable to set the API token.
# Be careful to not expose it in the travis logs
# If the example requires an existing experiment ID, use
# ./test/with_new_experiment and it will replace NEW_EXPERIMENT_ID with
# a newly created valid experiment
script:
  - ./test/run_python classifier classifier_tuner.py \
      --client-token $SIGOPT_API_TOKEN \
      --num-sigopt-suggestions 2 \
      --num-random-searches 1 \
      --grid-search-width 1
  - ./test/with_new_experiment ./test/run_python other-languages other_languages.py \
      --command "../test/other_languages_tester" \
      --client_token $SIGOPT_API_TOKEN \
      --experiment_id NEW_EXPERIMENT_ID
