sudo: false
language: python
python:
  - "2.7"
  - "3.5"
# TODO(patrick): Test on OSX, python is not supported on travis yet
# os:
  # - linux
  # - osx
cache:
  pip: true

# Use the SIGOPT_API_TOKEN environment variable to set the API token.
# Be careful to not expose it in the travis logs
script:
  - ./test/run_python classifier classifier_tuner.py \
      --client-token $SIGOPT_API_TOKEN \
      --num-sigopt-suggestions 2 \
      --num-random-searches 1 \
      --grid-search-width 1
